### ISSUE TITLE
shellphish-qemu-cgc install failed

### ISSUE THREAD

**Issue by SOSCapture** [shellphish/shellphish-qemu#3]
/home/yzb/Downloads/shellphish-qemu-master/shellphish-qemu-cgc-base/linux-user/main.c:64:2: error: #error 32-on-64 only
 #error 32-on-64 only
  ^
/home/yzb/Downloads/shellphish-qemu-master/shellphish-qemu-cgc-base/linux-user/main.c: In function ‘handle_predump’:

/home/yzb/Downloads/shellphish-qemu-master/shellphish-qemu-cgc-base/linux-user/main.c:539:22: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
         predump_file = arg;
                      ^
make[1]: *** [linux-user/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [subdir-i386-linux-user] Error 2

**Comment by SOSCapture** [comment]
How to fix this problem?please give me some advices.

**Comment by zardus** [comment]
Are you on a 32-bit machine on a 64-bit one?

**Comment by SOSCapture** [comment]
32-bit machine.should I change a 64-bit one?

**Comment by rhelmot** [comment]
Yes. This package is only designed to work on 64-bit Ubuntu.

**Comment by SOSCapture** [comment]
But my angr platform works well in 32-bit Ubuntu,while facing  Segmentation fault (core dumped) problem in 64-bit Ubuntu.

**Comment by SOSCapture** [comment]
Is there any ideas to fix this problem ? I am really grateful if you can give me some help to install the driller plateform. @rhelmot

**Comment by zardus** [comment]
32-bit is very much unsupported. I think you should try to fix the issues you're having on 64-bit.
